server:
  port: 8082
  servlet:
    path:


spring:
  messages:
    encoding: UTF-8
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/test1?useSSL=false
     username: root
     password: root

  thymeleaf:
    cache: false

    prefix: classpath:/templates/Backstage/
    suffix: .html
    mode: HTML5
