server:
  port: 80
  servlet:
    path: /

web:
  upload=path: /usr/local/upload/

spring:
  messages:
    encoding: UTF-8
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name:  com.mysql.jdbc.Driver
     url: jdbc:mysql://47.94.81.127/hyzj?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
     username: hyzjdba
     password: hyzjprogroup

  thymeleaf:
    cache: false
    prefix: classpath:/templates/Backstage/
    suffix: .html

  resources:
    static-locations: classpath:/static/,file:${web.upload=path},classpath:/templates/Backstage/

