server:
  port: 8080
  servlet:
    path: /


spring:
  messages:
    encoding: UTF-8
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name:  com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://47.94.81.127/hyzj?useSSL=false
     username: hyzjdba
     password: hyzjprogroup

  thymeleaf:
    cache: false

    prefix: classpath:/templates/Backstage/
    suffix: .html
    mode: HTML5
